services:
  langflow:
    build: .
    volumes:
      - ./app:/app:rw  # Volume original pour le code
      - ./data:/data:rw  # Nouveau volume pour SQLite
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_HOST=${LANGFLOW_HOST}
      - DATABASE_URL=${LANGFLOW_DATABASE_URL}
      # Langfuse (si nécessaire)
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
    networks:
      - langflow-network

networks:
  langflow-network:
    driver: bridge