services:
  langflow:
    image: langflowai/langflow:latest
    restart: always
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow_password@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=/app/config
    volumes:
      - ./config:/app/config:cached
      - ./data:/app/langflow:cached
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=langflow
      - POSTGRES_PASSWORD=langflow_password
      - POSTGRES_DB=langflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow"]
      interval: 10s
      timeout: 5s
      retries: 5